server:
  port:8080
mybatis:
  mapperLocations: classpath:mapper/*.xml
spring:
#数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
#logging:
#  level:
#    com.jwj.study.spring.application.transaction.cas : debug
